import "./globals.css";

export const metadata = {
  title: "Grama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-full bg-[var(--background)]">
        {children}
      </body>
    </html>
  );
}
