FROM node:20.13.0-alpine3.18

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED 1

COPY ./grama .
COPY ./prisma .
COPY ./docker/grama_entrypoint.sh .

RUN chmod +x grama_entrypoint.sh

RUN \
  if [ -f package-lock.json ]; then \
    npm ci --legacy-peer-deps; \
  else \
    echo "package-lock.json not found." ; exit 1; \
  fi


ENTRYPOINT ["./grama_entrypoint.sh"]